### ISSUE TITLE
Screen flashing with old view

### ISSUE THREAD

**Issue by m52go** [shprink/ionic-native-transitions#44] opened 2015-12-09 22:53 UTC
Transitions seem to work great, but there's a flashing/flickering of the old view after the animation. I haven't seen this mentioned anywhere...is this a known issue?

Or perhaps I'm doing something wrong. This is running on a phsyical Nexus 6 with 5.1. All I did was include the plug-in and set some defaults (I tried lots of `duration` and `androiddelay` and `slowdownfactor` combinations too):

```
.config(function($ionicNativeTransitionsProvider){
    $ionicNativeTransitionsProvider.setDefaultOptions({
        "duration"          : 200,
        "androiddelay"      : -1, // Longer delay better for older androids
    });
})
```

Video:

[![video here](http://img.youtube.com/vi/8BmY7enopUo/0.jpg)](http://www.youtube.com/watch?v=8BmY7enopUo)

**Comment by shprink** [comment] 2015-12-09 23:15
Can you remove all your custom options, see if it helps. The default should work.

The recommended plugin versions is rc-5 for this plugin and 5.5 for telerik native transitions.

**Comment by shprink** [comment] 2015-12-09 23:16
Also if you use crosswalk be careful to add that: https://github.com/shprink/ionic-native-transitions#android

**Comment by m52go** [comment] 2015-12-10 01:07
Thanks for your quick help. I already had the Crosswalk preference set. I removed it just now (just for fun) and animations totally disappeared.

I removed all custom options and it seemed to help a little, but the issue remains.

What's the difference between your plugin and the telerik one? I ran:

`ionic plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.5.5`

Is there a way I can just directly install your plugin?

I'll try other devices once I'm home. But the Nexus 6 should (generally) have high performance.

**Comment by shprink** [comment] 2015-12-10 03:31
You must have something unique in your state definition. It is hard for me to reproduce so I will wait for your investigation. Thanks very much.

**Comment by shadowed87** [comment] 2015-12-14 19:32
I have the same problem, maybe because we are using tabs?

these are my states

```
  //abstract state for the tabs directive
                    .state('tab', {
                        url: '/tab',
                        abstract: true,
                        controller: 'appCtrl',
                        templateUrl: 'templates/tabs.html',
                    })

// Each tab has its own nav history stack:
                    .state('tab.feeds', {
                        url: '/feeds',
                        views: {
                            'tab-feeds': {
                                templateUrl: 'templates/tab-feeds.html',
                                controller: 'FeedsCtrl'
                            }
                        }
                    })

                    .state('tab.feeds-recipe', {
                        url: '/feeds/recipe/:recipeId',
                        views: {
                            'tab-feeds': {
                                templateUrl: 'templates/recipe-view.html',
                                controller: 'RecipeCtrl'
                            }
                        }})

                    .state('tab.feeds-recipebook', {
                        url: '/feeds/recipebook/:username',
                        views: {
                            'tab-feeds': {
                                templateUrl: 'templates/recipebook-view.html',
                                controller: 'RecipebookCtrl'
                            }
                        }
                    })

                    .state('tab.profile', {
                        url: '/profile',
                        views: {
                            'tab-profile': {
                                templateUrl: 'templates/tab-profile.html',
                                controller: 'ProfileCtrl'
                            }
                        }
                    })

                    .state('tab.settings', {
                        url: '/settings',
                        views: {
                            'tab-settings': {
                                templateUrl: 'templates/tab-settings.html',
                                controller: 'SettingsCtrl'
                            }
                        }
                    });
```

I really made many tries, with all possible configurations.... @m52go I hope you manage to go somewhere

**Comment by ZoRDoK** [comment] 2015-12-30 08:06
Similar issue.

On Zenfone 2 (Atom, PowerVR) blinking is very short. But on HTC M8 (Snapdragon, Adreno) too laggy.

**Comment by AdrienDC** [comment] 2016-01-04 10:42
Same issue here, I can see a white blinking on transition even with default options set

**Comment by abacaj** [comment] 2016-01-07 15:28
Same issue here

**Comment by AdrienDC** [comment] 2016-01-08 08:23
Hi,
I use the following options on Android and it's a way better, I don't have the blinking issue although it creates an other issue when you go out of your tabs page (see https://github.com/driftyco/ionic/issues/2997). It seems the "ionicView.enter" state is not fired anymore when you go out and in to your tabs view. Should work though if you only have tab views.

        $ionicNativeTransitionsProvider.setDefaultOptions({
            duration: 200, // in milliseconds (ms), default 400,
            slowdownfactor: 1, // overlap views (higher number is more) or no overlap (1), default 4
            iosdelay: 400, // ms to wait for the iOS webview to update before animation kicks in, default -1
            androiddelay: 400, // same as above but for Android, default -1
            winphonedelay: 400, // same as above but for Windows Phone, default -1,
            fixedPixelsTop: 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
            fixedPixelsBottom: 0, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
            triggerTransitionEvent: 'ionicView.enter', // internal ionic-native-transitions option
            backInOppositeDirection: false // Takes over default back transition and state back transition to use the opposite direction transition to go back
        });

**Comment by shprink** [comment] 2016-01-08 13:57
I think this problem happens because the ionic enter event is trigger too
early. Would a additional delay set via the options help?

**Comment by AdrienDC** [comment] 2016-01-11 11:00
If I put additional delay, I feels really not native... ~500ms should be the maximum to put.

**Comment by shprink** [comment] 2016-01-19 14:49
A solution might have been found in #55. Can you please try and let us know?

**Comment by susanlinsfu** [comment] 2016-02-09 17:57
+1 I am also experiencing this issue. I created a brand new ionic project with just two views. Each view had a different background color and a button to go to the other view.  The flickering happens, although not always consistent. I have all default options on. I noticed if I set the duration to something high like 2000ms the flickering stops.

**Comment by susanlinsfu** [comment] 2016-02-10 07:01
I tried setting the full screen parameter to true but it did not help.

**Comment by m52go** [comment] 2016-02-10 17:40
For the record, since it's been mentioned a couple of times here, I'm not using tabs. 

I'm not clear about the solution in #55 but I've asked for clarification in that thread. I'll report back here if I gain any progress.

**Comment by cleever** [comment] 2016-02-11 23:51
Same issue here.

**Comment by susanlinsfu** [comment] 2016-02-12 18:28
I have a real simple ionic app with 2 views. They transition into each other and the issue is occuring on a real device. https://drive.google.com/open?id=0B_Bg9bA0eE0BU0ZzeVRoUFFFWFU

**Comment by shprink** [comment] 2016-02-12 18:33
Thanks for sharing, which platform have you tried @susanlinsfu ?

**Comment by susanlinsfu** [comment] 2016-02-12 21:25
@shprink  This on android 5.0 (Motorola g phone 1st generation which is a lower end phone).

**Comment by nverdhan** [comment] 2016-02-13 10:12
Most probably, the bug is due to view-caching in ionic. Once, I removed view caching by setting `cache:false` in my routes file, the screen flickering with old view bug was gone.

However, I still get the bug for those views where I need cache.

**Comment by susanlinsfu** [comment] 2016-02-13 10:26
I tried turning off the cache inside of my application (all routes have cache set to false) and the bug still occurs.

**Comment by jeremygomez** [comment] 2016-02-18 04:40
Same issue here. Here is my scenario (using an Ionic tab navigation app)...

1. start on main view of one of the tabs.
2. drill down to a secondary view of the same tab.
3. navigate to another tab.
4. go back to the first tab and you will see the secondary view (step 2 above) flash quickly before the native transition starts back to the main view of the tab.

Setting `cache: false` on my routes sort of fixes the issue, but now instead of the secondary view flashing, it shows a blank screen quickly before transitioning to the main tab view. A little better, but still not ideal. Not to mention other issues (not related) with not caching my routes.

**Comment by cvaliere** [comment] 2016-02-26 11:43
+1

**Comment by p1ng** [comment] 2016-03-02 20:19
+1

**Comment by cvaliere** [comment] 2016-03-02 21:04
Here is a screen record of what happens.
To see it well, I have used androidDelay=5000 and duration=10000

![ezgif-2411372577](https://cloud.githubusercontent.com/assets/5433779/13475344/91f67c5c-e0c2-11e5-89c4-edd7c6e95e18.gif)

**Comment by tiagoabelha** [comment] 2016-03-04 17:23
Same issue here testing on Moto 3G Lolipop 5.1.1. In other older devices with Android 4.2 and 4.3 and with Crosswalk this issue of the flashing content is not happening in an app i'm developing. 

As a workaround (the flashing was happening when changing from one view, with a ion-list with ng-repeat and lots of elements, to other specific view), i added in the 1st controller:

`$scope.$on('$ionicView.beforeLeave', function(scopes, states) {
   angular.element(document.getElementsByClassName("scroll-content")).addClass('hidden');
});`

and in the second controller in $ionicView.afterEnter i removed the class 'hidden' after a timeout of 50 ms. This consistently solved the issue in the device i'm testing.

**Comment by nvigneux** [comment] 2016-04-11 15:23
+1

**Comment by harellevy** [comment] 2016-04-12 16:21
+1

**Comment by Alexintosh** [comment] 2016-04-14 10:07
Same problem here, the flicker it's kind of annoying

**Comment by cvaliere** [comment] 2016-04-14 13:21
is there anything we can do to help?
I'd love to use this plugin, but it's just not possible with this flicker

**Comment by shprink** [comment] 2016-04-14 14:06
You could try to determine if it is a problem with this plugin or a problem with telerik's plugin.

**Comment by p1ng** [comment] 2016-04-14 17:12
this issue in the telerik plugin seems to be the same problem:  https://github.com/Telerik-Verified-Plugins/NativePageTransitions/issues/124.  I didn't see a commit that fixed it though so I'm not sure why they closed it.

**Comment by shprink** [comment] 2016-04-14 17:19
you guys go put +1s over there lol

**Comment by hossam9995** [comment] 2016-04-22 11:45
+1 ANY solution

**Comment by p1ng** [comment] 2016-04-22 12:57
hey @hossam9995 - my _workaround_ is to just use fade instead of slide for now.  It's not a fix, but it allowed me to move past this.

**Comment by hossam9995** [comment] 2016-04-23 09:29
@p1ng  i will try the fade thanks

**Comment by shprink** [comment] 2016-06-07 08:29
Should be fixed with RC11 #97. Please let us know if it is not the case

**Closed by shprink** 2016-06-07 08:29 UTC

**Comment by rpcarnell** [comment] 2016-09-25 09:16
Can you have a background image with this? When there is a transition flip, a background image can be seen?

**Comment by tosmos** [comment] 2017-02-19 16:30
Please help me.
When i used native transition, it shows next page first and running transition next,so next pages was showed twice. how to solve it.
I used option like this.

$ionicNativeTransitionsProvider.setDefaultOptions({
    duration: 200, // in milliseconds (ms), default 400,
    slowdownfactor: 1, // overlap views (higher number is more) or no overlap (1), default 4
    iosdelay: -1, // ms to wait for the iOS webview to update before animation kicks in, default -1
    androiddelay: -1, // same as above but for Android, default -1
    winphonedelay: -1, // same as above but for Windows Phone, default -1,
    fixedPixelsTop: 0, // the number of pixels of your fixed header, default 0 (iOS and Android)
    fixedPixelsBottom: 0, // the number of pixels of your fixed footer (f.i. a tab bar), default 0 (iOS and Android)
    triggerTransitionEvent: 'ionicView.enter', // internal ionic-native-transitions option
    backInOppositeDirection: false // Takes over default back transition and state back transition to use the opposite direction transition to go back
});
