### ISSUE TITLE
hardware back button

### ISSUE THREAD

**Issue by ln206** [shprink/ionic-native-transitions#39] opened 2015-12-01 01:49 UTC
Back button using ion-nav-back-button is working properly except for hardware back button. For example, when I transition to another state, the screen swipe to the left, when I click ion-nav-back-button, the screen swipes to the right, but when I click the hardware's back button, it still swipe to the left ( supposed to be to the right like the ion-nav-back-button).

**Comment by SMarijic** [comment] 2015-12-02 10:46
I have the same problem too.

**Comment by outerbound** [comment] 2015-12-03 06:30
facing the same issue.  Tap on back button on nav bar works as expected but android hardware backbutton does not.

**Comment by elliotstokes** [comment] 2015-12-03 11:09
+1 same problem here.

**Comment by shprink** [comment] 2015-12-03 14:26
Does any of you have enough technical background to try to debug it?

**Comment by SMarijic** [comment] 2015-12-03 14:33
@shprink I did spent yesterday few hours debugging Javascript part, I don't think it's problem there, options variable get's populated with data that were set trough setDefaultBackTransition method.

**Comment by shprink** [comment] 2015-12-03 14:43
Can any of you send me your app in debug mode via email?

**Comment by SMarijic** [comment] 2015-12-03 15:21
@shprink My app is 50MB+ in size

**Comment by elliotstokes** [comment] 2015-12-03 15:38
Im guessing the problem will show itself on this template

https://github.com/driftyco/ionic-starter-tabs

**Comment by SMarijic** [comment] 2015-12-03 16:47
@shprink Here is the fix:

Istead of:
   $ionicPlatform.onHardwareBackButton(goBackHardware);

put this
$ionicPlatform.registerBackButtonAction(function () 
{
	goBackHardware();
}, 100);

second parameter is priority, and only function with highest priority gets executed. I tested that only on emulator, but I think it will also work on device.

**Comment by shprink** [comment] 2015-12-03 17:02
hum nice! @SMarijic thanks for that, did not know about this second argument

**Comment by gartorware** [comment] 2015-12-03 17:18
Wow, I can confirm the bug and the fix posted by @SMarijic . Just tested it on real device and it's working like a charm.

**Comment by shprink** [comment] 2015-12-03 17:31
ok let me fix it real quick then

**Comment by shprink** [comment] 2015-12-03 17:38
I have tested, it breaks the fact that when a modal, an actionsheet or the menu is open, the back button should close it instead of going back to the previous state :(

**Comment by shprink** [comment] 2015-12-03 17:39
wait a minute it could be my mistake!

**Comment by shprink** [comment] 2015-12-03 17:40
testing : 

```
$ionicPlatform.onHardwareBackButton((hasCanceledUi) => goBackHardware(hasCanceledUi), 100);
```

**Comment by shprink** [comment] 2015-12-03 17:45
v1.0.0-rc4 is out. please check if it fixes this issue and close it accordingly.

**Comment by gartorware** [comment] 2015-12-03 17:56
Just installed rc4 and it's not working for me :(, the bug is back (again on real device). And I confirm too that behaviour is wrong with open menu using the previous fix.

I'm going to test it on another project too.

**Comment by outerbound** [comment] 2015-12-03 18:01
onHardwareBackButton does not have priority parameter. Only registerBackButtonAction has.
see http://ionicframework.com/docs/api/service/$ionicPlatform/

**Comment by gartorware** [comment] 2015-12-03 18:12
Nope, another test in another project and bug still occurs. 

Weird enough, I have replaced this:
$ionicPlatform.onHardwareBackButton((hasCanceledUi) => goBackHardware(hasCanceledUi), 100);

with the previous version:
$ionicPlatform.onHardwareBackButton(goBackHardware);

Then I have tested  @SMarijic fix again and behaviour is as expected with open menus. Not tested modal or actionsheet though. Menu is closing on back button press and transitions are the expected one too.

**Comment by shprink** [comment] 2015-12-03 18:19
Good catch @outerbound , I need to use `registerBackButtonAction` which I do not so far (maybe for a good reason, can't remember).

**Comment by SMarijic** [comment] 2015-12-03 19:06
@gartorware @shprink So did my fix helped you guys or?

**Comment by gartorware** [comment] 2015-12-04 06:43
Yes, in my case the fix is complete. Back button has the right behaviour and opened menu is closed rightly. Not tested with modal though. 

In order to work I have to apply your fix to rc3 version.

**Comment by gartorware** [comment] 2015-12-04 06:59
In fact, reviewing the docs there should be no problem with the fix since default priorities are as below: (see http://ionicframework.com/docs/api/service/%24ionicPlatform/)

The priorities for the existing back button hooks are as follows:
Return to previous view = 100
Close side menu = 150
Dismiss modal = 200
Close action sheet = 300
Dismiss popup = 400
Dismiss loading overlay = 500

Only one action is fired per back button press and highest values have more priority so with a value of 100, modal, menu, action sheet, ect. Should still be closed before firing a transition.

Let's hope there isn't any drawback on registering back button.

**Comment by SMarijic** [comment] 2015-12-04 07:08
I had same case, my only problem was going back to back view, so I've tested only that, but according to this priority list, there should be no problems with modal, menu etc.

**Comment by addi90** [comment] 2015-12-04 08:02
The problem still exists with `ionic-native-transitions#~1.0.0-rc4 ` but the below change to `ionic-native-transitions#~1.0.0-rc3` works fine:
```
//$ionicPlatform.onHardwareBackButton(goBackHardware);
 $ionicPlatform.registerBackButtonAction(function ()
 {
   goBackHardware();
 }, 100);
```

**Comment by shprink** [comment] 2015-12-04 10:26
OK i'll fix that in the airport in few hours. Thanks everyone

**Comment by shprink** [comment] 2015-12-04 12:43
Working hard for you guys!

![image](https://cloud.githubusercontent.com/assets/1388706/11589945/43820304-9a52-11e5-86ae-6dd83080354e.png)

**Comment by shprink** [comment] 2015-12-04 12:51
Alright I made this commit: https://github.com/shprink/ionic-native-transitions/commit/dacb9bec8567226c41729d5bc1a755fd4db8cd6e

It should now be fine with rc5, please let me know and close accordingly.

**Comment by SMarijic** [comment] 2015-12-04 13:38
Working fine for back transition :) Thnaks

**Comment by gartorware** [comment] 2015-12-04 14:07
+1
All working right now! Thank you very much!!

**Comment by ln206** [comment] 2015-12-04 18:13
Thank you very much!!!

**Comment by shprink** [comment] 2015-12-04 18:48
that's awesome! if you guys have any idea how to the same thing with the
ios swipe back I am all ears

**Comment by SMarijic** [comment] 2015-12-04 20:45
@shprink Maybe we could Gestures from ionic, on-swipe events?

**Comment by shprink** [comment] 2015-12-04 21:14
any of you know if we can intercept swipe back events?

**Comment by SMarijic** [comment] 2015-12-04 21:19
I' not sure, since there is no such event, because ionic uses on-drag. Why would you want to intercept it?

**Comment by shprink** [comment] 2015-12-04 21:41
to cancel it and trigger a native back transition but if there is not such
a callback accessible then that's nit a good idea

**Comment by SMarijic** [comment] 2015-12-04 22:01
@shprink  I agree on that, but maybe it would not be terrible idea to try it and see how it behaves, we wouldn't do any hack. Turn off ionic swipe back callback trough $ionicConfigProvider.views.swipeBackEnabled(false);

and then replicate same checks ionic uses to decide whether to trigger transition or not

**Comment by shprink** [comment] 2015-12-05 00:28
@SMarijic I will try to use ionicGesture as you proposed.

**Comment by shprink** [comment] 2015-12-05 00:28
#41 is open to fix swipe back on IOS, thanks everyone

**Closed by shprink** 2015-12-05 00:28 UTC
Labels: bug

**Comment by tbro028** [comment] 2015-12-06 23:47
I can't exit the app using the hardware back button - anyone else got this issue?

**Comment by NgYueHong** [comment] 2015-12-07 00:42
> Working hard for you guys!
Thanks sphrink. The world couldn't be better without people like you...

**Comment by dgmedia** [comment] 2016-03-23 17:33
Hey shprink. Great work with the plugin! Love the transitions! Just wanted to say that this bug is back.

I tried rc10 and hardware back button caused the right transition (right - left) whereas rc5 works correct (with the left-right).

**Comment by SrijithRad** [comment] 2016-03-23 17:37
Hey sphrink. Great work with the plugin! Love the transitions! Just wanted to say that this bug is back.

I tried rc10 and hardware back button caused the right transition (right - left) whereas rc5 works correct (with the left-right).

Tested on Android 4.4.2 and 5.0.1

**Comment by juanf9224** [comment] 2016-04-21 14:59
Hey @shprink, registerBackButton doesn't work when using native transitions.
`$ionicPlatform.registerBackButtonAction(function(e){
e.preventDefault();
})`

without native-transitions it works just fine, any idea why this is happening?

**Comment by shprink** [comment] 2016-04-21 15:21
What is the purpose of `e.preventDefault();` ? You do not want the back button to go back?

**Comment by juanf9224** [comment] 2016-04-21 15:58
Exactly, i dont want it to go back on top levels, i updated my question from earlier, i was able to make it work setting a priority to 501, although it is still not working as it used to with priority set to 100, but its ok. Thanks for replying!

**Comment by shprink** [comment] 2016-04-21 16:49
Why do not you remove the back button then (trying to understand)?

**Comment by juanf9224** [comment] 2016-04-21 17:07
I want it to work on non top level paths, ie: 

app/home -> don't want back exiting app, instead i'm opening side menu when user presses back hardware button on top level paths

app/home/something -> i want back to work and navigate back to home

sorry if didn't explained myself clear. xD

**Comment by shprink** [comment] 2016-04-21 17:15
ok make sense thanks

**Comment by nevace** [comment] 2016-07-15 12:48
Hmmm I'm experiencing this issue although it has already been fixed and closed. Back button works fine but the hardware button uses the transition of the page rather than 'backInOppositeDirection' transition.

If I use the navbar back button, the 'backInOppositeDirection' transition is fine.

I'm trying it on Android 5.1.1 and have the latest version of your library (1.0.0) via Bower.

**Comment by ladmerc** [comment] 2016-08-27 19:36
I'm having the same issue as @nevace

**Comment by chandu7929** [comment] 2017-04-07 13:02
$ionicPlatform.registerBackButtonAction(function() {

    if ($rootScope.backButtonPressedOnceToExit && $state.is('home')) {
      ionic.Platform.exitApp();
    } else if ($ionicHistory.backView()) {
      $ionicNativeTransitions.stateGo($ionicHistory.backView().stateName, {}, {}, {
        "type": "slide",
        "direction": "up", // 'left|right|up|down', default 'left' (which is like 'next') 
        "duration": 600, // in milliseconds (ms), default 400 
      });
      //$ionicHistory.goBack();
    } else {
      $rootScope.backButtonPressedOnceToExit = true;
      $cordovaToast.showShortCenter("Press back button again to exit");

      setTimeout(function() {
        $rootScope.backButtonPressedOnceToExit = false;
      }, 2000);
    }
    e.preventDefault();
    return false;

  }, 101);
