### ISSUE TITLE
iOS Sim works but device is broken

### ISSUE THREAD

**Issue by dwilt** [shprink/ionic-native-transitions#63] opened 2016-01-27 19:51 UTC
![screenshot 2016-01-27 10 27 04](https://cloud.githubusercontent.com/assets/1065539/12626137/054a5798-c4ec-11e5-820d-19fd8c24fd7c.png)

Ran the `bower install`, then `ionic plugin add https://github.com/Telerik-Verified-Plugins/NativePageTransitions#0.5.5`, then updated my `index.js` accordingly. Opened up the iOS sim and I'm seeing the transitions fine but when I build to test on the phone, the Xcode build is failing. Any thoughts?

**Comment by shprink** [comment] 2016-01-27 21:02
maybe disable bitcode.

**Comment by dwilt** [comment] 2016-01-27 21:20
@shprink how do I do that?

**Comment by shprink** [comment] 2016-01-27 21:24
Try that https://github.com/shprink/wordpress-hybrid-client/blob/develop/BUILD.md#ios9

**Comment by dwilt** [comment] 2016-01-28 19:19
This actually might not be this plugin. I'll get back shortly.

**Comment by shprink** [comment] 2016-01-28 19:21
I dot think it is, closing till you find the root cause

**Closed by shprink** 2016-01-28 19:21 UTC
